version: '3.8'
services:

  rabbitmq:
    image: rabbitmq:3.5.3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    networks:
      - e-banking-network

  zipkin-server:
    image: openzipkin/zipkin
    container_name: zipkin
    environment:
      STORAGE_TYPE: mem
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    ports:
      - "9411:9411"
    restart: always
    depends_on:
      - rabbitmq
    networks:
      - e-banking-network

  netflix-eureka-naming-server:
    image: e-banking/eureka:0.0.1-SNAPSHOT
#    build:
#      context: netflix-eureka-naming-server
#      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    restart: always
    networks:
      - e-banking-network

  netflix-zuul-api-gateway-server:
    image: e-banking/zuul:0.0.1-SNAPSHOT
#    build:
#      context: netflix-zuul-api-gateway-server
#      dockerfile: Dockerfile
    ports:
      - "8762:8762"
    restart: always
    depends_on:
      - netflix-eureka-naming-server
      - rabbitmq
      - zipkin-server
    networks:
      - e-banking-network

  user-service:
    image: e-banking/user:0.0.1-SNAPSHOT
#    build:
#      context: user-service
#      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - netflix-eureka-naming-server
      - rabbitmq
      - zipkin-server
    networks:
      - e-banking-network

  bank-account-service:
    image: e-banking/bank-account:0.0.1-SNAPSHOT
#    build:
#      context: bank-account-service
#      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      - netflix-eureka-naming-server
      - rabbitmq
      - zipkin-server
    networks:
      - e-banking-network

  insurance-service:
    image: e-banking/insurance:0.0.1-SNAPSHOT
#    build:
#      context: insurance-service
#      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    restart: always
    depends_on:
      - netflix-eureka-naming-server
      - rabbitmq
      - zipkin-server
    networks:
      - e-banking-network

networks:
  e-banking-network: