version: '3.7'
services:

  netflix-eureka-naming-server:
    build:
      context: netflix-eureka-naming-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    restart: always
    networks:
      - e-banking-network

  netflix-zuul-api-gateway-server:
    build:
      context: netflix-zuul-api-gateway-server
      dockerfile: Dockerfile
    ports:
      - "8762:8762"
    restart: always
    depends_on:
      - netflix-eureka-naming-server
    networks:
      - currency-compose-network

  user-service:
    build:
      context: user-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - netflix-eureka-naming-server
    networks:
      - e-banking-network

  bank-account-service:
    build:
      context: bank-account-service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      - netflix-eureka-naming-server
    networks:
      - e-banking-network

    insurance-service:
      build:
        context: insurance-service
        dockerfile: Dockerfile
      ports:
        - "8002:8002"
      restart: always
      depends_on:
        - netflix-eureka-naming-server
      networks:
        - e-banking-network

networks:
  e-banking-network: